name: Container Build

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 2 * * *'

permissions: write-all

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    strategy:
      matrix:
        version: [1.23.5,1.24,latest]

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Registry Login
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Convert IMAGE_NAME to lowercase
      id: lowercase
      run: echo "IMAGE_NAME=$(echo ${{ env.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Map version to tag
      id: map
      run: |
        case "${{ matrix.version }}" in
          "1.23.5") echo "tag=1.23.5" >> $GITHUB_OUTPUT ;;
          "1.24.0") echo "tag=1.24.0" >> $GITHUB_OUTPUT ;;
          "latest") echo "tag=latest" >> $GITHUB_OUTPUT ;;
        esac

    - name: Build and Push
      run: docker buildx build --build-arg GOLANG_VERSION=${{ matrix.version }} --platform linux/amd64 -t "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.map.outputs.tag }}" --push -f Dockerfile .
